import Head from 'next/head'
import News from "@/components/News.js";
import Nav from "@/components/Nav.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | News homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Nav/>
      <main >
        <News/>
      </main>
    </>
  )
}
